[pytest]
minversion = 8.0

# Show extra summary info for (x)failed, (x)passed, and (s)kipped tests
addopts = -ra --strict-markers

# Where to look for tests
testpaths =
    tests

# Test discovery rules
python_files = test_*.py
python_classes = Test*
python_functions = test_*
