# SubOS Kubernetes manifest
apiVersion: v1
kind: Namespace
metadata:
  name: subos

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subos-config
  namespace: subos
  labels: { app: subos }
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 512Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subos-memory
  namespace: subos
  labels: { app: subos }
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subos-deployment
  namespace: subos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subos
  template:
    metadata:
      labels:
        app: subos
    spec:
      containers:
        - name: subos
          image: ghcr.io/dylanlrpollock/hueyos:subos
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1995
              name: http1995
          volumeMounts:
            - name: config
              mountPath: /workspace/config
            - name: memory
              mountPath: /workspace/memory
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: subos-config
        - name: memory
          persistentVolumeClaim:
            claimName: subos-memory

---
apiVersion: v1
kind: Service
metadata:
  name: subos-service
  namespace: subos
spec:
  selector:
    app: subos
  ports:
    - name: http1995
      port: 1995
      targetPort: 1995
  type: ClusterIP
